### ISSUE TITLE
Bugs on wintx.py and wintx_flask.py

### ISSUE THREAD

**Issue by Jaewoo-Shin** [MacaroonCookie/wintx#1]
1. Near the line 167 in query_polygon(), wintx_flask.py file.
if( 'query' in request.args ):
    query_dict = formQuery(request.args['filter’])
I think ‘query’ needs to be changed to the filter (or ‘filter’ needs to be changed to be ‘query’)

2. From the line 674 in wintx.py
records = self.__queryAllShards__(query)
records = self.__finalizeRecords__(results, sort_column)

I think the first var ‘records’ needs to be changed to ‘results’ to be passed to __finalizeRecords__(results, sort_column);

**Comment by MacaroonCookie** [comment]
This has been fixed in Wintx 1.05
