### ISSUE TITLE
Getting available dates from database.

### ISSUE THREAD

**Issue by Jaewoo-Shin** [MacaroonCookie/wintx#2]
Hello, 
This is Jaewoo Shin.
I have a question for the wintx library and wintxflask.

Currently, we want to add a feature to the wintx app: 
Show only available dates on the calendar, so user can select only the available dates.

To get this, I reviewed the wintx.py and wintxflask.py and I think there is no way to get distinct dates from the database yet.
Because there are over 150 dates in the database, I think it would be nice to get available dates via RESTful API through WintxFlask.

Could you please add that feature to the Wintx and WintxFlask?

Thanks and Best Regards,

Jaewoo Shin

**Comment by MacaroonCookie** [comment]
The functionality has been incorporated into Wintx and the Wintx REST API.
