### ISSUE TITLE
HTTPS issue.

### ISSUE THREAD

**Issue by Jaewoo-Shin** [MacaroonCookie/wintx#3]
Hello,

I have a question for the wintx flask with HTTPS.
When the wintx in the component try to fetch json data from squall server, it returns error because the hub component is served as HTTPS, but squall server provide HTTP (see. following error message)
 
Mixed Content: The page at 'https://dev.mygeohub.org/groups/geoshare/wintx' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://squall.rcac.purdue.edu:5000/metadata/variables'. This request has been blocked; the content must be served over HTTPS.

Could you please modify the flask to support the HTTPS protocol?
I think this link( http://flask.pocoo.org/snippets/111/ ) could be helpful for this issue.

**Comment by MacaroonCookie** [comment]
SSL encryption of the Wintx REST service is handled through WSGI deployment. To enable encryption, submit a request for your deployment service to handle this.
